### ISSUE TITLE
Add CSRF tokens

### ISSUE THREAD

**Issue by kristianbinau** [OurUncomplicatedTemplates/fastify-prisma-redis-swagger-jwt-template#16]
We need to fix our CSRF issue that we introduced by setting `sameSite: "none"`.

**Accept-test**
* Fix CSRF issue

**Comment by frederikpyt** [comment]
Closing issue, see https://github.com/OurUncomplicatedTemplates/fastify-prisma-redis-swagger-jwt-template/pull/17 for explanation
